### ISSUE TITLE
Errors in Documentation

### ISSUE THREAD

**Issue by michaelcrain** [fuzzybabybunny/microscope-orionjs#1]
Thanks much for this OrionJS guide. It's been very helpful.  I did find a few spots that ether need correcting or looking into.
1.  The "/client/templates/orion/comments_index_blurb_cell.html" reference for the template helper code should be a .js file not .html.
2. The "hasOne" and "hasMany" attribute required me to "$ meteor add orionjs:relationships" the package, which wasn't mentioned in the doc.
3.  For some reason the ... collection: 'Posts', ... of the Comments.attachSchema "hasOne" example throws "ReferenceError: Posts is not defined"

Thanks again for this guide. It saved me quite a bit of time.

**Comment by fuzzybabybunny** [comment]
Good eye! The tutorial has been updated. Give it a go!
